services:
  # Client configuration
  - type: web
    name: freepdf2jpg-client
    env: node
    buildCommand: cd client && npm install && npm run build
    startCommand: cd client && npm start
    envVars:
      - key: VITE_API_URL
        value: https://freepdf2jpg-server.onrender.com/api
      - key: NODE_ENV
        value: production

  # Server configuration
  - type: web
    name: freepdf2jpg-server
    env: docker
    dockerfilePath: ./server/Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGIN
        value: https://freepdf2jpg.ca 