services:
  - type: web
    name: freepdf2jpg-server
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: PORT
        value: 5001
  - type: web
    name: freepdf2jpg-client
    env: node
    buildCommand: npm run build
    startCommand: serve -s dist
    staticPublishPath: client/dist
    plan: free
    autoDeploy: true
