services:
  # Client configuration
  - type: static
    name: freepdf2jpg-client
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/dist
    headers:
      - source: /**
        headers:
          - key: Cache-Control
            value: no-cache
    envVars:
      - key: VITE_API_URL
        value: https://freepdf2jpg-server.onrender.com/api

  # Server configuration
  - type: web
    name: freepdf2jpg-server
    env: docker
    dockerfilePath: ./server/Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGIN
        value: https://freepdf2jpg.ca 