services:
  # Client configuration
  - type: web
    name: freepdf2jpg-client
    env: static
    buildCommand: |
      cd client
      npm install
      npm run build
      cp public/404.html dist/
    staticPublishPath: ./client/dist
    headers:
      - source: /*
        headers:
          - key: Cache-Control
            value: no-cache
    routes:
      - type: rewrite
        source: /about
        destination: /index.html
      - type: rewrite
        source: /contact
        destination: /index.html
      - type: rewrite
        source: /pdf-to-jpg
        destination: /index.html
      - type: rewrite
        source: /jpg-to-pdf
        destination: /index.html
      - type: rewrite
        source: /qa
        destination: /index.html
      - type: rewrite
        source: /privacy-policy
        destination: /index.html
      - type: rewrite
        source: /terms-of-service
        destination: /index.html
      - type: rewrite
        source: /*
        destination: /404.html
        status: 404
    envVars:
      - key: VITE_API_URL
        value: https://freepdf2jpg-server.onrender.com/api

  # Server configuration
  - type: web
    name: freepdf2jpg-server
    env: docker
    dockerfilePath: ./server/Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGIN
        value: https://freepdf2jpg.ca 